# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['save_editor.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets\\T_Icon_Items_Normal.png',      'assets'),
        ('assets\\T_Icon_Items_Highlight.png',   'assets'),
        ('assets\\T_Icon_Runes_Normal.png',      'assets'),
        ('assets\\T_Icon_Runes_Highlight.png',   'assets'),
        ('assets\\T_Icon_ArrowsBolts_Normal.png','assets'),
        ('assets\\T_Icon_ArrowsBolts_Highlight.png','assets'),
        ('assets\\T_Icon_Quests_Normal.png',     'assets'),
        ('assets\\T_Icon_Quests_Highlight.png',  'assets'),
        ('assets\\T_Inventory_EquipmentHelmet.png','assets'),
        ('assets\\T_Inventory_EquipmentBody.png','assets'),
        ('assets\\T_Inventory_EquipmentLegs.png','assets'),
        ('assets\\T_Inventory_EquipmentCape.png','assets'),
        ('assets\\T_Inventory_EquipmentTrinket.png','assets'),
        ('assets\\PowerLevel1.png',              'assets'),
        ('assets\\PowerLevel2.png',              'assets'),
        ('assets\\PowerLevel3.png',              'assets'),
        ('assets\\PowerLevel4.png',              'assets'),
        ('assets\\T_Icons_Journal_Recipes_Resources_VaultCore.png','assets'),
        ('assets\\T_Icon_Rune_Law.png',          'assets'),
        ('assets\\T_Arrows_Bone.png',            'assets'),
        ('assets\\T_Icons_Journal_Imbued_Maul_Head.png','assets'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    exclude_binaries=False,
    name='Dragonwilds Editor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
